# Generated by Django 3.2.3 on 2021-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffe',
            new_name='Coffee',
        ),
    ]
