# Generated by Django 3.2.3 on 2021-05-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_coffe_coffee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='is_idce',
            new_name='is_ice',
        ),
    ]
